version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000" # Map host port 8000 to container's PHP-FPM port 9000
    depends_on:
      - db
    environment:
      # Laravel environment variables, ensure they match your .env
      DB_CONNECTION: mysql
      DB_HOST: db # Name of the database service in docker-compose.yaml
      DB_PORT: 3306
      DB_DATABASE: larlab-starter-kits
      DB_USERNAME: root
      DB_PASSWORD: password

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" # Map host port 80 to container's Nginx port 80
    volumes:
      - .:/var/www/html
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab-starter-kits

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
